export const JOB_CATEGORIES = [
  "Computer & Mobile",
  "Beauty & Salon",
  "Banking",
  "Teaching",
  "Supermarket & Retail",
  "Laundry & Ironing",
  "Factory & Production", 
  "Repair & Fixing",
  "Cleaning & Housekeeping",
  "Security & Watchman",
  "Tailoring & Clothing",
  "Verification and Checking",
  "Software Development",
  "Web Development",
  "Mobile App Development",
  "Data Science & Analytics",
  "Artificial Intelligence (AI)",
  "Machine Learning (ML)",
  "Cloud Computing",
  "Cybersecurity",
  "Network Engineering",
  "DevOps",
  "Quality Assurance (QA)",
  "UI/UX Design",
  "Product Management",
  "Project Management",
  "Technical Support",
  "IT Administration",
  "Database Administration",
  "Game Development",
  "Embedded Systems",
  "Digital Marketing",
  "Content Writing",
  "Sales & Marketing",
  "Human Resources",
  "Finance & Accounting",
  "Customer Service",
  "Healthcare",
  "Education",
  "Manufacturing",
  "Logistics & Supply Chain",
  "Construction",
  "Retail",
  "Hospitality",
  "Arts & Culture",
  "Non-profit",
  "Legal",
  "Consulting",
  "Research",
  "Other",
];
