export const JOB_CATEGORIES = [
  "Software Development",
  "Web Development",
  "Mobile App Development",
  "Data Science & Analytics",
  "Artificial Intelligence (AI)",
  "Machine Learning (ML)",
  "Cloud Computing",
  "Cybersecurity",
  "Network Engineering",
  "DevOps",
  "Quality Assurance (QA)",
  "UI/UX Design",
  "Product Management",
  "Project Management",
  "Technical Support",
  "IT Administration",
  "Database Administration",
  "Game Development",
  "Embedded Systems",
  "Digital Marketing",
  "Content Writing",
  "Sales & Marketing",
  "Human Resources",
  "Finance & Accounting",
  "Customer Service",
  "Healthcare",
  "Education",
  "Manufacturing",
  "Logistics & Supply Chain",
  "Construction",
  "Retail",
  "Hospitality",
  "Arts & Culture",
  "Non-profit",
  "Legal",
  "Consulting",
  "Research",
  "Other",
];
